In [1]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import OneClassSVM
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Load the Iris dataset
iris = datasets.load_iris()
iris_df = pd.DataFrame(data=np.c_[iris['data'], iris['target']],
                       columns=iris['feature_names'] + ['target'])

In [3]:
# Feature Selection
features = iris['feature_names']

In [4]:
# Split the data into training and testing sets
train_data, test_data = train_test_split(iris_df, test_size=0.2, random_state=42)

In [5]:
# Preprocessing
def preprocess_data(data, features):
    X = data[features]
    y = data['target']
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    return X_scaled, y

In [6]:
# Train a One-Class SVM model
def train_ocsvm(X_train):
    ocsvm_model = OneClassSVM(kernel='rbf', nu=0.05)  # You can adjust the 'nu' parameter
    ocsvm_model.fit(X_train)
    return ocsvm_model

In [7]:
# Evaluate the model
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    y_pred = np.where(y_pred == 1, 0, 1)  # Convert labels to binary (0: normal, 1: outlier)
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    matrix = confusion_matrix(y_test, y_pred)
    return accuracy, report, matrix

In [9]:
# Preprocess the training data
X_train_scaled, y_train = preprocess_data(train_data, features)

In [10]:
# Train a One-Class SVM model
ocsvm_model = train_ocsvm(X_train_scaled)

In [11]:
# Preprocess the test data
X_test_scaled, y_test = preprocess_data(test_data, features)

In [12]:
# Evaluate the model
accuracy, report, confusion_matrix = evaluate_model(ocsvm_model, X_test_scaled, y_test)
print(f'Accuracy of the model on the test set: {accuracy:.2f}')
print('\nClassification Report:')
print(report)
print('\nConfusion Matrix:')
print(confusion_matrix)

Accuracy of the model on the test set: 0.37

Classification Report:
              precision    recall  f1-score   support

         0.0       0.37      1.00      0.54        10
         1.0       0.33      0.11      0.17         9
         2.0       0.00      0.00      0.00        11

    accuracy                           0.37        30
   macro avg       0.23      0.37      0.24        30
weighted avg       0.22      0.37      0.23        30


Confusion Matrix:
[[10  0  0]
 [ 8  1  0]
 [ 9  2  0]]


C:\Users\rvign\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rvign\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\rvign\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result)